<select name="" class="form-control">
    <option value="INR" selected>₹ India Rupees</option>
    <option value="USD"><span>&#36;</span> United States Dollars</option>
    <option value="EUR"><span>&#8364;</span> Euro</option>
    <option value="GBP"><span>&#163;</span> United Kingdom Pounds</option>
    <option value="DZD">دج  Algeria Dinars(دينار جزائري)</option>
    <option value="ARP"><span>&#36;</span>  Argentina Pesos(Peso argentino)</option>
    <option value="AUD">A$ Australia Dollars</option>
    <option value="BSD">B$ Bahamas Dollars</option>
    <option value="BBD">Bds$ Barbados Dollars</option>
    <option value="BMD">$ Bermuda Dollars</option>
    <option value="BRR">R$ Brazil Real(Real brasileiro)</option>
    <option value="BGL">лв Bulgaria Lev(Български лев)</option>
    <option value="CAD">C$ Canada Dollars</option>
    <option value="CLP">$ Chile Pesos(Peso chileno)</option>
    <option value="CNY"><span>&#20803;</span> China Renminbi(人民币)</option>
    <option value="CSK">Kč Czech Republic Koruna(koruna česká)</option>
    <option value="DKK">kr. Denmark Kroner(dansk krone)</option>
    <option value="XCD">EC$ Eastern Caribbean Dollars</option>
    <option value="EGP">ج.م Egypt Pounds(جنيه مصرى)</option>
    <option value="FJD">FJ$ Fiji Dollars</option>
    <option value="HKD"><span>&#22291;</span> Hong Kong Dollars(港元)</option>
    <option value="HUF">Ft Hungary Forint(magyar forint)</option>
    <option value="ISK">kr Iceland Krona(króna)</option>
    <option value="IDR">Rp Indonesia Rupiah</option>
    <option value="ILS">₪ Israel New Shekels(שקל חדש)</option>
    <option value="JMD">$ Jamaica Dollars</option>
    <option value="JPY"><span>&#165;</span> Japan Yen(日本円)</option>
    <option value="JOD">د.أ Jordan Dinar(عشرة قروش أردنيه)</option>
    <option value="KRW">₩ Korea Won(대한민국 원)</option>
    <option value="LBP">ل.ل Lebanon Pounds(ليرة لبنانية)</option>
    <option value="MYR">RM Malaysia Ringgit(Ringgit Malaysia)</option>
    <option value="MXP">Mex$ Mexico Pesos(Peso Mexicano)</option>
    <option value="NZD">NZ$ New Zealand Dollars</option>
    <option value="NOK">kr,,- Norway Krone(norsk krone)</option>
    <option value="PKR">₨ Pakistan Rupees</option>
    <option value="PHP">₱ Philippines Pesos(Piso ng Pilipinas)</option>
    <option value="PLN">zł Poland Zloty(Polski złoty)</option>
    <option value="ROL">L Romania Leu(Leu românesc)</option>
    <option value="RUR">₽ Russia Rubles(Российский рубль)</option>
    <option value="SAR">ر.س Saudi Arabia Riyal(ريال سعودي)</option>
    <option value="SGD">S$ Singapore Dollars</option>
    <option value="ZAR">R South Africa Rand</option>
    <option value="SEK">kr Sweden Krona(svensk krona)</option>
    <option value="CHF">CHF Switzerland Francs(Schweizer Franken)</option>
    <option value="TWD"><span>&#22291;</span> Taiwan Dollars(新台幣)</option>
    <option value="UAH">₴ Ukraine Hryvnia(українська гривня)</option>
    <option value="THB">฿ Thailand Baht(บาทไทย)</option>
    <option value="TTD">TT$ Trinidad and Tobago Dollars</option>
    <option value="TRL">₺ Turkey Lira(Türk lirası)</option>
    <option value="VEB">Bs Venezuela Bolivar(bolívar venezolano)</option>
    <option value="ZMK">ZK Zambia Kwacha</option>
</select>